services:
  node-server:
    image: ghcr.io/zkadish/cra-express-gh-actions/cra-express-node:latest
    # ports:
    #   - "4001:3001"
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  nginx-server:
    image: ghcr.io/zkadish/cra-express-gh-actions/nginx-node-proxy:latest
    ports:
      - "81:80"
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 5s
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
