services:
  node-server:
    image: ghcr.io/zkadish/cra-express-gh-actions/cra-express-node:latest
    # ports:
    #   - "4001:3001"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  nginx-server:
    image: ghcr.io/zkadish/cra-express-gh-actions/cra-express-nginx:latest
    ports:
      - "81:80"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
