services:
  node-server:
    image: ghcr.io/zkadish/cra-express-node:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  nginx-server:
    image: ghcr.io/zkadish/nginx-proxy:latest
    ports:
      - "81:80"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
