services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile-node
    # Only expose the node layer directly when testing the application
    # Never expose the node layer in Deployed environments
    # ports:
    #   - "4001:3001"
  nginx-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "81:80"
