FROM node:18.18.1-alpine3.17

WORKDIR /usr/src/app
COPY . ./
RUN cd client/ && yarn && yarn run build
RUN cd client/ && cp -r build/. ../server/public
# Do not allow node server to be exposed out side of
# the docker network in deployed environments
# EXPOSE 4001 
WORKDIR /usr/src/app/server
RUN yarn cache clean && yarn --update-checksums
CMD ["yarn", "start"]