FROM node:18.18.1-alpine3.17 as NodeImage

WORKDIR /usr/src/app
COPY . ./
RUN cd client/ && yarn && yarn run build
RUN cd client/ && cp -r build/. ../server/public
# EXPOSE 4001
WORKDIR /usr/src/app/server
RUN yarn cache clean && yarn --update-checksums
# CMD ["yarn", "start"]

FROM nginx:1.24.0-alpine3.17
COPY --from=NodeImage
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]