name: Build the Server and Run tests

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
      - name: Use Node.js 18.18.1
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.18.1"
      - name: Install yarn and start server
        run: |
          cd server/
          yarn
          yarn start
